<?php
/**
 * @category   India
 * @package    India_Bazar
 * @author     subham845415@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace India\Bazar\Block;

use Magento\Framework\View\Element\Template\Context;
use India\Bazar\Model\BazarFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Bazar View block
 */
class BazarView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Bazar
     */
    protected $_bazar;
    public function __construct(
        Context $context,
        BazarFactory $bazar,
        FilterProvider $filterProvider
    ) {
        $this->_bazar = $bazar;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('India Bazar Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $bazar = $this->_bazar->create();
        $singleData = $bazar->load($id);
        if($singleData->getBazarId() || $singleData['bazar_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}