<?php
/**
 * @category   India
 * @package    India_Bazar
 * @author     subham845415@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace India\Bazar\Block;

use Magento\Framework\View\Element\Template\Context;
use India\Bazar\Model\BazarFactory;
/**
 * Bazar List block
 */
class BazarListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Bazar
     */
    protected $_bazar;
    public function __construct(
        Context $context,
        BazarFactory $bazar
    ) {
        $this->_bazar = $bazar;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('India Bazar Module List Page'));
        
        if ($this->getBazarCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'india.bazar.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getBazarCollection()
            );
            $this->setChild('pager', $pager);
            $this->getBazarCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getBazarCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $bazar = $this->_bazar->create();
        $collection = $bazar->getCollection();
        $collection->addFieldToFilter('status','1');
        //$bazar->setOrder('bazar_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}